#The name of your workflow.
name: build
# Trigger the workflow on push or pull request
on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  # uil
  build:
    defaults:
        run:
          working-directory: ./
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: cd example/
      - run: flutter test
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /high_chart/